
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftMainBinding ///

public protocol SwiftMainBinding: JavaProtocol {

}


open class SwiftMainBindingForward: JNIObjectForward, SwiftMainBinding {

    private static var SwiftMainBindingJNIClass: jclass?

}

